name: Build and Push Backend Service Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'services/backend/**'
  workflow_dispatch:

jobs:
  build-image:
    name: Build & Push 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and Push Docker Image
        run: |
          cd services/backend
          source service-version.sh
          echo "Building and pushing Docker image for backend"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:$BACKEND_VERSION . 
          docker tag ${{ secrets.DOCKER_USERNAME }}/backend:$BACKEND_VERSION ${{ secrets.DOCKER_USERNAME }}/backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:$BACKEND_VERSION
